-- Celestial dragon Drops
-- Generated by RS3 Monster Drop Scraper
-- Scraped at: 2025-10-26T13:17:08.043Z
-- Total drops: 32

local Celestial_dragon_drops = {536, 31189, 30930, 30933, 30936, 30939, 30943, 44807, 59209, 1754, 1752, 1750, 1748, 6156, 995,
               47075, 47314, 1443, 1445, 238, 37227, 42008, 42009, 42010, 11286, 18778, 36814, 12158, 12159, 12160,
               12163, 24154}

return Celestial_dragon_drops
