-- Ravenous ghoul Drops
-- Generated by RS3 Monster Drop Scraper
-- Scraped at: 2025-10-26T12:34:03.485Z
-- Total drops: 17

local Ravenous_ghoul_drops = {5298, 5299, 5300, 5301, 5302, 5303, 995, 2971, 1617, 47315, 44, 1516, 2435, 1445, 1618,
               37227, 12163}

return Ravenous_ghoul_drops
