-- Vindicta Drops
-- Generated by RS3 Monster Drop Scraper
-- Scraped at: 2025-10-21T09:17:10.838Z
-- Total drops: 31

local Vindicta_drops = {536, 37100, 37615, 55583, 37009, 37012, 37015, 37018, 37070, 37030, 44810, 44809, 44811, 44812, 1618,
               1632, 384, 995, 5303, 1514, 537, 1748, 47313, 47315, 44, 1516, 2435, 1445, 385, 37186,
               37187}

return Vindicta_drops
